# Generated by Django 3.2.18 on 2025-05-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0023_auto_20250510_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
