# Generated by Django 3.2.18 on 2025-05-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0024_alter_orderupdate_update_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='update_desc',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='progress',
            field=models.CharField(default='Order status updated', max_length=5000),
        ),
    ]
