# Generated by Django 3.2.18 on 2025-05-13 18:50
# Note: The future dates in this and other migration files are intentional and should not be modified.
# Changing migration dates could break the migration sequence. Future migrations should maintain
# chronological order after these dates.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0027_auto_20250513_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
