# Generated by Django 3.2.18 on 2025-05-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0028_alter_shipping_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Shipment', 'verbose_name_plural': 'Shipments'},
        ),
        migrations.AlterModelOptions(
            name='orderupdate',
            options={'verbose_name': 'Shipment Update', 'verbose_name_plural': 'Shipment Updates'},
        ),
        migrations.AlterModelOptions(
            name='pending_order',
            options={'verbose_name': 'Pending Shipment', 'verbose_name_plural': 'Pending Shipments'},
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='custom_date',
            field=models.CharField(blank=True, help_text='Format: Month-Date-Year (e.g., January-15-2025)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='custom_time',
            field=models.CharField(blank=True, help_text='Format: HH:MM AM/PM (e.g., 02:30 PM)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='status',
            field=models.CharField(choices=[('Placed Order', 'Placed Shipment'), ('Confirmed Order', 'Confirmed Shipment'), ('Picked-up', 'Picked-up'), ('Dispatched Product', 'Dispatched Product'), ('Reached Product', 'Reached Product'), ('Delivered Product', 'Delivered Product')], default='Placed Order', max_length=50),
        ),
        migrations.AlterField(
            model_name='pending_order',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
