# Generated by Django 3.2.18 on 2025-05-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0029_auto_20250515_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='custom_date',
            field=models.CharField(blank=True, help_text='Format: Day, Date Month, Year (e.g., Tue, 13 Jan, 2025)', max_length=50, null=True),
        ),
    ]
